# ExamItems
# 生化学的検査
ExamItem.create!(formal_name: '総蛋白', abbreviation: 'TP')
ExamItem.create!(formal_name: 'アルブミン', abbreviation: 'ALB')
ExamItem.create!(formal_name: 'クンケル', abbreviation: 'ZTT')
ExamItem.create!(formal_name: 'チモール', abbreviation: 'TTT')
ExamItem.create!(formal_name: '総ビリルビン', abbreviation: 'T-BIL')
ExamItem.create!(formal_name: '直接ビリルビン', abbreviation: 'D-BIL')
ExamItem.create!(formal_name: 'アルカリホスファターゼ', abbreviation: 'ALP')
ExamItem.create!(formal_name: 'γ-GT', abbreviation: 'GGTP')
ExamItem.create!(formal_name: 'AST', abbreviation: 'GOT')
ExamItem.create!(formal_name: 'ALT', abbreviation: 'GPT')
ExamItem.create!(formal_name: 'LD', abbreviation: 'LDH')
ExamItem.create!(formal_name: '総コレステロール', abbreviation: 'T-CHO')
ExamItem.create!(formal_name: '中性脂肪', abbreviation: 'TG')
ExamItem.create!(formal_name: 'LDL-コレステロール', abbreviation: 'LDL-C')
ExamItem.create!(formal_name: 'HDL-コレステロール', abbreviation: 'HDL-C')
ExamItem.create!(formal_name: '尿素窒素', abbreviation: 'BUN')
ExamItem.create!(formal_name: 'クレアチニン', abbreviation: 'CRE')
ExamItem.create!(formal_name: '推算GFRcreat', abbreviation: '')
ExamItem.create!(formal_name: '尿酸', abbreviation: 'UA')
ExamItem.create!(formal_name: 'ナトリウム', abbreviation: 'NA')
ExamItem.create!(formal_name: 'カリウム', abbreviation: 'K')
ExamItem.create!(formal_name: 'クロール', abbreviation: 'CL')
ExamItem.create!(formal_name: 'カルシウム', abbreviation: 'CA')
ExamItem.create!(formal_name: 'P(無機リン)', abbreviation: '')
ExamItem.create!(formal_name: 'アミラーゼ', abbreviation: 'AMY')
ExamItem.create!(formal_name: '尿アミラーゼ(部分尿)', abbreviation: 'AMY/U')
ExamItem.create!(formal_name: '鉄(Fe)', abbreviation: '')
ExamItem.create!(formal_name: 'TIBC', abbreviation: '')
ExamItem.create!(formal_name: 'UIBC', abbreviation: '')
ExamItem.create!(formal_name: 'フェリチン', abbreviation: '')
ExamItem.create!(formal_name: '蛋白分画', abbreviation: '')
ExamItem.create!(formal_name: 'A/G', abbreviation: '')
ExamItem.create!(formal_name: 'コリンエステラーゼ', abbreviation: '')
ExamItem.create!(formal_name: 'LAP', abbreviation: '')
ExamItem.create!(formal_name: 'CK', abbreviation: 'CPK')
ExamItem.create!(formal_name: 'KL-6', abbreviation: '')
ExamItem.create!(formal_name: 'グリコアルブミン', abbreviation: '')
ExamItem.create!(formal_name: '血糖 空腹時', abbreviation: '')
ExamItem.create!(formal_name: '1.5AG', abbreviation: '')
ExamItem.create!(formal_name: 'アンモニア', abbreviation: '')
ExamItem.create!(formal_name: 'マグネシウム', abbreviation: '')
ExamItem.create!(formal_name: '亜鉛(Zn)', abbreviation: '')
ExamItem.create!(formal_name: 'ビタミンB12', abbreviation: '')
ExamItem.create!(formal_name: '葉酸', abbreviation: '')
ExamItem.create!(formal_name: 'リパーゼ', abbreviation: '')
ExamItem.create!(formal_name: 'ヒアルロン酸', abbreviation: '')
ExamItem.create!(formal_name: '尿中NTX', abbreviation: '')
ExamItem.create!(formal_name: '尿中DPD', abbreviation: '')
ExamItem.create!(formal_name: 'BAP', abbreviation: '')
ExamItem.create!(formal_name: '血清NTX', abbreviation: '')
ExamItem.create!(formal_name: 'Ⅳ型コラーゲン7S', abbreviation: '')
ExamItem.create!(formal_name: 'NT-proBNP', abbreviation: '')
ExamItem.create!(formal_name: 'BNP', abbreviation: '')
ExamItem.create!(formal_name: 'LD(LDH)アイソザイム', abbreviation: '')
ExamItem.create!(formal_name: 'ALPアイソザイム', abbreviation: '')

# 尿・糞便検査
ExamItem.create!(formal_name: '尿一般検査', abbreviation: '')
ExamItem.create!(formal_name: '尿沈渣', abbreviation: '')
ExamItem.create!(formal_name: '尿蛋白定量', abbreviation: '')
ExamItem.create!(formal_name: '尿糖定量', abbreviation: '')
ExamItem.create!(formal_name: '尿中アルブミン定量', abbreviation: '')
ExamItem.create!(formal_name: '便ヘモグロビン1日目', abbreviation: '')
ExamItem.create!(formal_name: '便ヘモグロビン2日目', abbreviation: '')

# 血液学的検査
ExamItem.create!(formal_name: '白血球数', abbreviation: 'WBC')
ExamItem.create!(formal_name: '赤血球数', abbreviation: 'RBC')
ExamItem.create!(formal_name: '血色素量', abbreviation: 'HB')
ExamItem.create!(formal_name: 'ヘマトクリット', abbreviation: 'HT')
ExamItem.create!(formal_name: '血小板数', abbreviation: '')
ExamItem.create!(formal_name: '網赤血球数', abbreviation: '')
ExamItem.create!(formal_name: '血液像5分画', abbreviation: '')
ExamItem.create!(formal_name: '血液像7分画', abbreviation: '')
ExamItem.create!(formal_name: 'HbA1c(NGSP)', abbreviation: 'HBA1C')
ExamItem.create!(formal_name: 'PT', abbreviation: '')
ExamItem.create!(formal_name: 'ARTT', abbreviation: '')
ExamItem.create!(formal_name: 'トロンボテスト', abbreviation: '')
ExamItem.create!(formal_name: 'フィブリノゲン', abbreviation: '')
ExamItem.create!(formal_name: 'FDP', abbreviation: '')
ExamItem.create!(formal_name: 'アンチトロンビンⅢ', abbreviation: '')
ExamItem.create!(formal_name: 'Dダイマー', abbreviation: '')

# 耐糖能関連検査
ExamItem.create!(formal_name: '血糖(前)', abbreviation: 'BS')
ExamItem.create!(formal_name: '血糖(30分)', abbreviation: '')
ExamItem.create!(formal_name: '血糖(60分)', abbreviation: '')
ExamItem.create!(formal_name: '血糖(90分)', abbreviation: '')
ExamItem.create!(formal_name: '血糖(120分)', abbreviation: '')
ExamItem.create!(formal_name: '血糖(150分)', abbreviation: '')
ExamItem.create!(formal_name: '血糖(180分)', abbreviation: '')
ExamItem.create!(formal_name: 'インスリン(前)', abbreviation: 'IRI')
ExamItem.create!(formal_name: 'インスリン(30分)', abbreviation: '')
ExamItem.create!(formal_name: 'インスリン(60分)', abbreviation: '')
ExamItem.create!(formal_name: 'インスリン(90分)', abbreviation: '')
ExamItem.create!(formal_name: 'インスリン(120分)', abbreviation: '')
ExamItem.create!(formal_name: 'インスリン(180分)', abbreviation: '')

# 免疫学的検査
ExamItem.create!(formal_name: 'ABO式血液型', abbreviation: '')
ExamItem.create!(formal_name: 'Rh(D)式血液型', abbreviation: '')
ExamItem.create!(formal_name: '(乳児)ABO式血液型', abbreviation: '')
ExamItem.create!(formal_name: 'ASO(定量)', abbreviation: '')
ExamItem.create!(formal_name: 'ASK(半定量)', abbreviation: '')
ExamItem.create!(formal_name: '寒冷凝集反応', abbreviation: '')
ExamItem.create!(formal_name: 'マイコプラズマ抗体(PA)', abbreviation: '')
ExamItem.create!(formal_name: '百日咳抗体(EIA)', abbreviation: '')
ExamItem.create!(formal_name: 'リウマトイド因子(RF定量)', abbreviation: '')
ExamItem.create!(formal_name: '抗ガラクトース欠損IgG抗体価', abbreviation: '')
ExamItem.create!(formal_name: '抗CCP抗体', abbreviation: '')
ExamItem.create!(formal_name: 'MMP-3', abbreviation: '')
ExamItem.create!(formal_name: 'CRP(定性)', abbreviation: 'CRP-1')
ExamItem.create!(formal_name: 'CRP(定量)', abbreviation: 'CRP-2')
ExamItem.create!(formal_name: '梅毒RPR(定性)', abbreviation: '')
ExamItem.create!(formal_name: '梅毒TP抗体(定性)', abbreviation: '')
ExamItem.create!(formal_name: '梅毒RPR(定量)', abbreviation: '')
ExamItem.create!(formal_name: '梅毒TPHA(定量)', abbreviation: '')
ExamItem.create!(formal_name: 'IgG', abbreviation: '')
ExamItem.create!(formal_name: 'IgA', abbreviation: '')
ExamItem.create!(formal_name: 'IgM', abbreviation: '')
ExamItem.create!(formal_name: '非特異的IgE', abbreviation: '')
ExamItem.create!(formal_name: '特異的IgE MAST36', abbreviation: '')
ExamItem.create!(formal_name: 'C3', abbreviation: '')
ExamItem.create!(formal_name: 'C4', abbreviation: '')
ExamItem.create!(formal_name: '血清補体価(CH50)', abbreviation: '')
ExamItem.create!(formal_name: '抗核抗体(ANA)', abbreviation: '')
ExamItem.create!(formal_name: '抗GAD抗体', abbreviation: '')
ExamItem.create!(formal_name: '抗SS-A/Ro抗体(CLEIA法)', abbreviation: '')
ExamItem.create!(formal_name: '抗SS-B/La抗体(CLEIA法)', abbreviation: '')

# ウイルス・感染症関連検査
ExamItem.create!(formal_name: 'HBs抗原(定性)', abbreviation: '')
ExamItem.create!(formal_name: 'HBs抗体(定性)', abbreviation: '')
ExamItem.create!(formal_name: 'HBs抗原(定量)', abbreviation: '')
ExamItem.create!(formal_name: 'HBs抗体(定量)', abbreviation: '')
ExamItem.create!(formal_name: 'HBe抗原', abbreviation: '')
ExamItem.create!(formal_name: 'HBe抗体', abbreviation: '')
ExamItem.create!(formal_name: 'IgM-HBc抗体', abbreviation: '')
ExamItem.create!(formal_name: 'HA抗体', abbreviation: '')
ExamItem.create!(formal_name: 'IgM-HA抗体', abbreviation: '')
ExamItem.create!(formal_name: 'HCV抗体(第3世代)', abbreviation: '')
ExamItem.create!(formal_name: 'HCV-RNA定量(RT-PCR)', abbreviation: '')
ExamItem.create!(formal_name: '風疹ウイルス抗体(HI)', abbreviation: '')
ExamItem.create!(formal_name: 'HIV1.2抗体', abbreviation: '')
ExamItem.create!(formal_name: 'ヘリコバクター・ピロリ抗体(定性)', abbreviation: '')
ExamItem.create!(formal_name: 'ヘリコバクター・ピロリIgG抗体(定量)', abbreviation: '')
ExamItem.create!(formal_name: '便中ヘリコバクターピロリ抗原', abbreviation: '')
ExamItem.create!(formal_name: '尿素呼気試験(ユービット)', abbreviation: '')
ExamItem.create!(formal_name: 'クラミジアトラコマディスDNA', abbreviation: '')
ExamItem.create!(formal_name: '淋菌DNA', abbreviation: '')
ExamItem.create!(formal_name: '淋菌クラミジア同時同定(PCR)', abbreviation: '')
ExamItem.create!(formal_name: 'β-Dグルカン', abbreviation: '')

# 腫瘍マーカー
ExamItem.create!(formal_name: 'CEA', abbreviation: '')
ExamItem.create!(formal_name: 'CA19-9', abbreviation: '')
ExamItem.create!(formal_name: 'AFP', abbreviation: '')
ExamItem.create!(formal_name: 'CA125', abbreviation: '')
ExamItem.create!(formal_name: 'PSA', abbreviation: '')
ExamItem.create!(formal_name: 'PSA(F/T比タンデム)', abbreviation: '')
ExamItem.create!(formal_name: 'TPA', abbreviation: '')
ExamItem.create!(formal_name: 'SCC', abbreviation: '')
ExamItem.create!(formal_name: 'PIVKA-Ⅱ', abbreviation: '')
ExamItem.create!(formal_name: 'エラスターゼ1', abbreviation: '')
ExamItem.create!(formal_name: 'NCC-ST-439', abbreviation: '')
ExamItem.create!(formal_name: 'DUPAN-2', abbreviation: '')
ExamItem.create!(formal_name: 'CA15-3', abbreviation: '')
ExamItem.create!(formal_name: 'BCA255', abbreviation: '')
ExamItem.create!(formal_name: 'シフラ', abbreviation: '')
ExamItem.create!(formal_name: '抗p53抗体', abbreviation: '')

# 甲状腺関連検査
ExamItem.create!(formal_name: 'T3', abbreviation: '')
ExamItem.create!(formal_name: 'T4', abbreviation: '')
ExamItem.create!(formal_name: 'Free T3', abbreviation: 'FT3')
ExamItem.create!(formal_name: 'Free T4', abbreviation: 'FT4')
ExamItem.create!(formal_name: 'TSH', abbreviation: '')
ExamItem.create!(formal_name: 'TSHレセプター抗体(第1世代TRAb)', abbreviation: '')
ExamItem.create!(formal_name: 'サイログロブリン', abbreviation: '')
ExamItem.create!(formal_name: '抗サイグロブリン抗体', abbreviation: '')
ExamItem.create!(formal_name: '抗TPO抗体', abbreviation: '')
ExamItem.create!(formal_name: 'TBG定量', abbreviation: '')
ExamItem.create!(formal_name: 'サイロイドテスト', abbreviation: '')
ExamItem.create!(formal_name: 'マイクロゾームテスト', abbreviation: '')

# 内分泌学的検査
ExamItem.create!(formal_name: 'LH', abbreviation: '')
ExamItem.create!(formal_name: 'FSH', abbreviation: '')
ExamItem.create!(formal_name: 'プロラクチン', abbreviation: '')
ExamItem.create!(formal_name: 'E2', abbreviation: '')
ExamItem.create!(formal_name: 'プロゲステロン', abbreviation: '')
ExamItem.create!(formal_name: 'テストステロン', abbreviation: '')
ExamItem.create!(formal_name: 'レニン活性', abbreviation: '')
ExamItem.create!(formal_name: 'コルチゾール', abbreviation: '')
ExamItem.create!(formal_name: 'アルドステロン', abbreviation: '')
ExamItem.create!(formal_name: 'ACTH', abbreviation: '')
ExamItem.create!(formal_name: 'カテコールアミン3分画', abbreviation: '')

# 薬物血中濃度検査
ExamItem.create!(formal_name: 'バルプロ酸', abbreviation: '')
ExamItem.create!(formal_name: 'フェニトイン', abbreviation: '')
ExamItem.create!(formal_name: 'フェノバルビタール', abbreviation: '')
ExamItem.create!(formal_name: 'カルバマゼビン', abbreviation: '')
ExamItem.create!(formal_name: 'ゾニサミド', abbreviation: '')
ExamItem.create!(formal_name: '炭酸リチウム', abbreviation: '')
ExamItem.create!(formal_name: 'ジゴキシン', abbreviation: '')
ExamItem.create!(formal_name: 'テオフィリン', abbreviation: '')
