FROM phusion/passenger-ruby25:1.0.3

RUN apt-get update -qq && \
    apt-get install -y nodejs \
    postgresql-client \
    graphviz \
    tzdata && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR /home/app/web
COPY --chown=app:app . /home/app/web
CMD rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 80
