FROM phusion/passenger-ruby26:1.0.6

# postgres,tzdataとasdfの依存関係をインストール
RUN apt-get update -qq && \
    apt-get install -y \
    postgresql-client graphviz tzdata bsdmainutils \
    automake autoconf libreadline-dev libncurses-dev libssl-dev libyaml-dev libxslt-dev libffi-dev libtool unixodbc-dev unzip curl && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# appユーザに切り替え
# RUN の利用時に asdf を読み込むため executable のプレフィックスも変更
USER app
SHELL ["/bin/bash", "-lc"]

# asdfのインストール
RUN git clone https://github.com/asdf-vm/asdf.git ~/.asdf && \
    cd ~/.asdf && \
    git checkout "$(git describe --abbrev=0 --tags)" && \
    sed -i '1i . $HOME/.asdf/asdf.sh' ~/.bashrc && \
    sed -i '1i . $HOME/.asdf/completions/asdf.bash' ~/.bashrc

# Node.js, yarnのプラグインをインストール
RUN asdf plugin-add nodejs https://github.com/asdf-vm/asdf-nodejs.git && \
    bash ~/.asdf/plugins/nodejs/bin/import-release-team-keyring && \
    asdf plugin-add yarn

# Railsプロジェクトのコピーと指定バージョンのNode.jsとyarnのインストール
COPY --chown=app:app . /home/app/web
WORKDIR /home/app/web
RUN asdf install

CMD ["rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0 -p 3000"]
